---

name: Advanced Commit Linter
description: Check if your commit messages are in correct format based on policy.

branding:
  icon: aperture
  color: green

inputs:
  pr-metadata:
    required: true
    default: ${{ github.event.number }}
    description: Pull Request metadata
  config-path:
    required: true
    default: .github/advanced-commit-linter.yml
    description: Path to configuration file

  set-status:
    required: true
    default: 'false'
    description: Set check-run status on Pull Request
  status-title:
    required: false
    default: Commit validation
    description: H3 title of status message
  token:
    required: true
    description: GitHub TOKEN or PAT

outputs:
  validated-pr-metadata:
    description: Original Pull Request metadata extended with validation data

runs:
  using: node20
  main: dist/index.js
