---

name: Advanced Commit Linter
description: Check if your commit messages are in correct format based on policy.

branding:
  icon: aperture
  color: green

inputs:
  pr-metadata:
    required: true
    description: Pull Request metadata
  token:
    required: true
    description: GitHub TOKEN or PAT

outputs:
  validated-pr-metadata:
    description: Original Pull Request metadata extended with validation data

runs:
  using: node16
  main: dist/index.js
